### ISSUE TITLE
Kyocera scanner - ECOSYS M2535dn

### ISSUE THREAD

**Issue by ScoobyMax** [openpaperwork/pyinsane#35]
Try to scan from ECOSYS M2535dn

[code]
```
C:\Python34\lib\site-packages\pyinsane2\wia\rawapi.py:105: RuntimeWarning: Pyinsane: WARNING: A property has a type different from the one expected
  properties = _rawapi.get_properties(dev_or_src)
Pyinsane: WARNING: A property has a type different from the one expected
Pyinsane: WARNING: A property has a type different from the one expected
C:\Python34\lib\site-packages\pyinsane2\wia\rawapi.py:116: RuntimeWarning: Pyinsane: WARNING: Got unknown clsid from driver
  constraints = _rawapi.get_constraints(dev_or_src)
Pyinsane: WARNING: Got unknown clsid from driver
Pyinsane: Failed to parse constraint of [item_category]
Constraint found on property [sti_driver_version] but property not found
Constraint found on property [scan_available_item] but property not found
C:\Python34\lib\site-packages\pyinsane2\wia\rawapi.py:116: RuntimeWarning: Pyinsane: WARNING: Unknown var type for constraint
  constraints = _rawapi.get_constraints(dev_or_src)
Pyinsane: WARNING: Unknown var type for constraint
Pyinsane: WARNING: Got unknown clsid from driver
Pyinsane: Failed to parse constraint of [item_category]
Pyinsane: WARNING: Got unknown clsid from driver
Pyinsane: Failed to parse constraint of [preferred_format]
Pyinsane: WARNING: Unknown var type for constraint
Pyinsane: WARNING: Got unknown clsid from driver
Pyinsane: Failed to parse constraint of [item_category]
Pyinsane: WARNING: Got unknown clsid from driver
Pyinsane: Failed to parse constraint of [preferred_format]
C:\Python34\lib\site-packages\pyinsane2\wia\rawapi.py:105: RuntimeWarning: Pyinsane: WARNING: Got unknown clsid from driver
  properties = _rawapi.get_properties(dev_or_src)
Pyinsane: WARNING: Got unknown clsid from driver
Pyinsane: WARNING: Unknown var type for constraint
Pyinsane: WARNING: Got unknown clsid from driver
Pyinsane: Failed to parse constraint of [item_category]
Pyinsane: WARNING: Got unknown clsid from driver
Pyinsane: Failed to parse constraint of [preferred_format]
Pyinsane: WARNING: A property has a type different from the one expected
Pyinsane: WARNING: A property has a type different from the one expected
Pyinsane: WARNING: Got unknown clsid from driver
Pyinsane: Failed to parse constraint of [item_category]
Constraint found on property [sti_driver_version] but property not found
Constraint found on property [scan_available_item] but property not found
Pyinsane: WARNING: Unknown var type for constraint
Pyinsane: WARNING: Got unknown clsid from driver
Pyinsane: Failed to parse constraint of [item_category]
Pyinsane: WARNING: Got unknown clsid from driver
Pyinsane: Failed to parse constraint of [preferred_format]
Pyinsane: WARNING: Unknown var type for constraint
Pyinsane: WARNING: Got unknown clsid from driver
Pyinsane: Failed to parse constraint of [item_category]
Pyinsane: WARNING: Got unknown clsid from driver
Pyinsane: Failed to parse constraint of [preferred_format]
Pyinsane: WARNING: Got unknown clsid from driver
Pyinsane: WARNING: Unknown var type for constraint
Pyinsane: WARNING: Got unknown clsid from driver
Pyinsane: Failed to parse constraint of [item_category]
Pyinsane: WARNING: Got unknown clsid from driver
Pyinsane: Failed to parse constraint of [preferred_format]
Got multiple time the option [current_intent], but they are not identical
Got multiple time the option [current_intent], but they are not identical
Option 'current_intent' preset to 'image_type_color,maximize_quality' on ['ECOSYS M2535dn' (Microsoft, Scanning System, scanner,streaming_video)]
Pyinsane: WARNING: A property has a type different from the one expected
Pyinsane: WARNING: A property has a type different from the one expected
Pyinsane: WARNING: Got unknown clsid from driver
Pyinsane: Failed to parse constraint of [item_category]
Constraint found on property [sti_driver_version] but property not found
Constraint found on property [scan_available_item] but property not found
Pyinsane: WARNING: Unknown var type for constraint
Pyinsane: WARNING: Got unknown clsid from driver
Pyinsane: Failed to parse constraint of [item_category]
Pyinsane: WARNING: Got unknown clsid from driver
Pyinsane: Failed to parse constraint of [preferred_format]
Pyinsane: WARNING: Unknown var type for constraint
Pyinsane: WARNING: Got unknown clsid from driver
Pyinsane: Failed to parse constraint of [item_category]
Pyinsane: WARNING: Got unknown clsid from driver
Pyinsane: Failed to parse constraint of [preferred_format]
Pyinsane: WARNING: Got unknown clsid from driver
Pyinsane: WARNING: Unknown var type for constraint
Pyinsane: WARNING: Got unknown clsid from driver
Pyinsane: Failed to parse constraint of [item_category]
Pyinsane: WARNING: Got unknown clsid from driver
Pyinsane: Failed to parse constraint of [preferred_format]
Got multiple time the option [current_intent], but they are not identical
Got multiple time the option [current_intent], but they are not identical
Option 'format' preset to 'bmp' on ['ECOSYS M2535dn' (Microsoft, Scanning System, scanner,streaming_video)]
Failed to pre-set option 'preferred_format' on ['ECOSYS M2535dn' (Microsoft, Scanning System, scanner,streaming_video)]
C:\Python34\lib\site-packages\pyinsane2\wia\rawapi.py:127: RuntimeWarning: Pyinsane: WARNING: properties->WriteMultiple() failed
  ret = _rawapi.set_property(dev_or_src, propname, propvalue)
Pyinsane: WARNING: properties->WriteMultiple() failed
Pyinsane: WARNING: properties->WriteMultiple() failed: page_size : 0x80070057
Exception while setting page_size: WIA: Failed to set scanner properties
WIA: Failed to set scanner properties
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\pyinsane2\wia\abstract.py", line 186, in _set_value
    rawapi.set_property(obj, self.name, new_value)
  File "C:\Python34\lib\site-packages\pyinsane2\wia\rawapi.py", line 134, in set_property
    propname=propname, propvalue=propvalue).wait()
  File "C:\Python34\lib\site-packages\pyinsane2\wia\rawapi.py", line 34, in wait
    raise self.exception
  File "C:\Python34\lib\site-packages\pyinsane2\wia\rawapi.py", line 39, in do
    self.result = self.func(**self.kwargs)
  File "C:\Python34\lib\site-packages\pyinsane2\wia\rawapi.py", line 129, in _set_property
    raise WIAException("Failed to set scanner properties")
pyinsane2.wia.rawapi.WIAException: WIA: Failed to set scanner properties
Pyinsane: WARNING: A property has a type different from the one expected
Pyinsane: WARNING: A property has a type different from the one expected
Pyinsane: WARNING: Got unknown clsid from driver
Pyinsane: Failed to parse constraint of [item_category]
Constraint found on property [sti_driver_version] but property not found
Constraint found on property [scan_available_item] but property not found
Pyinsane: WARNING: Unknown var type for constraint
Pyinsane: WARNING: Got unknown clsid from driver
Pyinsane: Failed to parse constraint of [item_category]
Pyinsane: WARNING: Got unknown clsid from driver
Pyinsane: Failed to parse constraint of [preferred_format]
Pyinsane: WARNING: Unknown var type for constraint
Pyinsane: WARNING: Got unknown clsid from driver
Pyinsane: Failed to parse constraint of [item_category]
Pyinsane: WARNING: Got unknown clsid from driver
Pyinsane: Failed to parse constraint of [preferred_format]
Pyinsane: WARNING: Got unknown clsid from driver
Pyinsane: WARNING: Unknown var type for constraint
Pyinsane: WARNING: Got unknown clsid from driver
Pyinsane: Failed to parse constraint of [item_category]
Pyinsane: WARNING: Got unknown clsid from driver
Pyinsane: Failed to parse constraint of [preferred_format]
Got multiple time the option [current_intent], but they are not identical
Got multiple time the option [page_size], but they are not identical
Got multiple time the option [current_intent], but they are not identical
Option 'page_size' preset to 'a4' on ['ECOSYS M2535dn' (Microsoft, Scanning System, scanner,streaming_video)]
Pyinsane: WARNING: A property has a type different from the one expected
Pyinsane: WARNING: A property has a type different from the one expected
Pyinsane: WARNING: Got unknown clsid from driver
Pyinsane: Failed to parse constraint of [item_category]
Constraint found on property [sti_driver_version] but property not found
Constraint found on property [scan_available_item] but property not found
Pyinsane: WARNING: Unknown var type for constraint
Pyinsane: WARNING: Got unknown clsid from driver
Pyinsane: Failed to parse constraint of [item_category]
Pyinsane: WARNING: Got unknown clsid from driver
Pyinsane: Failed to parse constraint of [preferred_format]
Pyinsane: WARNING: Unknown var type for constraint
Pyinsane: WARNING: Got unknown clsid from driver
Pyinsane: Failed to parse constraint of [item_category]
Pyinsane: WARNING: Got unknown clsid from driver
Pyinsane: Failed to parse constraint of [preferred_format]
Pyinsane: WARNING: Got unknown clsid from driver
Pyinsane: WARNING: Unknown var type for constraint
Pyinsane: WARNING: Got unknown clsid from driver
Pyinsane: Failed to parse constraint of [item_category]
Pyinsane: WARNING: Got unknown clsid from driver
Pyinsane: Failed to parse constraint of [preferred_format]
Got multiple time the option [current_intent], but they are not identical
Got multiple time the option [depth], but they are not identical
Got multiple time the option [page_size], but they are not identical
Got multiple time the option [current_intent], but they are not identical
Got multiple time the option [depth], but they are not identical
Option 'depth' preset to '24' on ['ECOSYS M2535dn' (Microsoft, Scanning System, scanner,streaming_video)]
```
and the program freezes

**Comment by jflesch** [comment]
Yeah, WIA support needs serious improvement/fixes. WIA API is kind of a mess ... every scanner has a slightly different behavior ... Unfortunately, the debug output won't be good enough to solve this problem.
I'm working on a [test program](https://github.com/openpaperwork/paperwork/issues/702) that will help me obtain a lot more information from as many people/scanners as possible. I'll keep you posted as soon as it's available.

**Comment by jflesch** [comment]
Hello,

[The test program is now ready. Can you give it a try please ?](http://openpaper.work/scanner_db/#contribute)
